project:
  type: website
  output-dir: docs

website:
  title: "Itsnatani Anaqami - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4
      - text: Labs 
        menu:
          - href: labs/lab0/scripts/lab0_template.qmd
            text: lab 0
          - href: labs/lab1/scripts/week3_lab_exercise.qmd
            text: lab 1

      - text: Assignments 
        menu:
          - href: assignments/assignment1/scripts/assignment1_template.qmd
            text: Assignment 1
          - href: assignments/assignment2/scripts/assignment2_template.qmd
            text: Assignment 2

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto